complete refactoring.
trinodb/trino-python-client pull request #64
Opened 2021-01-07 09:03 UTC by realknorke

replaced almost ever occurrence of "presto" with "trino".
README.md migrated, too -- except the Presto book link
changed default version of Trino for integration tests to 351

2021-01-07 09:09 UTC, realknorke commented
I used the code to execute some queries on our Trino351 cluster. Works.

2021-01-07 11:08 UTC, hashhar requested changes
Thanks for picking this up. ❤️ 

There are some non-rename changes in the same commit. I'd like if you could extract them into a separate commit at the end.

Also, some changes requested.

2021-01-07 11:08 UTC, hashhar commented on README.md
> +$ pip install trino-client
```suggestion
$ pip install trino
```

https://pypi.org/project/trino/

2021-01-07 11:08 UTC, hashhar commented on integration_tests/test_dbapi.py
> +    with trino_connection_with_transaction as connection:
Split this change into two commits. One with just the rename and the next one with the refactoring.

Thanks for catching this.

2021-01-07 11:08 UTC, hashhar commented on trino/constants.py
> +DEFAULT_SOURCE = "Trino-python-client"
Is the case change intentional?

2021-01-08 08:38 UTC, realknorke commented on trino/constants.py
> +DEFAULT_SOURCE = "Trino-python-client"
fixed. sharp eyes! :)
thanks

2021-01-08 11:29 UTC, hashhar commented on integration_tests/test_dbapi.py
> +    with trino_connection_with_transaction as connection:
Nevermind about this, I misread the diff.

2021-01-08 11:29 UTC, hashhar approved these changes
Looks good to me.

Would love a second pair of eyes - specifically the HTTP header changes.

2021-01-08 12:17 UTC, merged

2021-01-08 12:17 UTC, findepi commented
Merged, thanks!

2022-01-16 20:50 UTC, callado4 commented
Is there a way to configure the header values? It seems that the sever I'm using is returning headers with the presto value, such as `'X-Presto-Added-Prepare': 'st_...`

2022-01-17 01:50 UTC, ebyhr commented
@callado4 I would recommend upgrading your cluster. Trino Python client doesn't provide the way to configure those values.

2022-01-17 06:35 UTC, hashhar commented
@callado4 While you upgrade the cluster you can use `pip install presto-client==0.302.0` (the last version that works with PrestoSQL) - note that it doesn't have any of the fixes made to trino-python-client over the last year. I also highly recommend to upgrade your cluster.