Added initial SQLAlchemy dialect for Trino
trinodb/trino-python-client pull request #76
Opened 2021-02-03 18:20 UTC by joshthoward

2021-02-03 18:22 UTC, joshthoward commented
Once Python 2.7 and 3.5 support are dropped we should be able to merge.

2021-02-03 21:08 UTC, findepi commented
> joshthoward requested a review from findepi 2 hours ago


i understand this is blocked yet. So will appreciate ping once unblocked. Thanks for understanding.

2021-02-04 03:25 UTC, joshthoward commented
@findepi understandable, but it's ready for review none the less. I would appreciate your opinion on the changes to the client.py and dbapi.py files in order to achieve compatibility as well as the sqlalchemy connection string (tests/test_sqalchemy_url.py). Please take a look when you find the time.

2021-03-18 03:40 UTC, dungdm93 requested changes

2021-03-18 03:40 UTC, dungdm93 commented on trino/sqlalchemy.py
> +        try:
Should use `SHOW TABLES 'table_name'` instead

2021-03-18 03:40 UTC, dungdm93 commented on trino/sqlalchemy.py
> +        rows = self._get_table_columns(connection, table_name, schema)
Should get columns from `<table>$partitions`. See [Hive special tables](https://trino.io/docs/current/connector/hive.html#special-tables)

2021-03-18 03:45 UTC, dungdm93 commented on setup.py
> +sqlalchemy_require = ["SQLAlchemy==1.3.22"]
Should we use dependency range `~=` or `>=` instead of specific version like this?

2021-04-14 20:45 UTC, closed without merging